baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'PASTORS AND MINISTERS FELLOWSHIP INTERNATIONAL pamfi.org'
theme = 'hugo-universal-theme'
 disqusShortname = "devcows"
    


#######################about us menu##################
[[main]]

[[menu.main]]
    name       = "ABOUT US"
    identifier = "menu.aboutus"
    url        = "/"
    weight     = 1
[[menu.main]]
    name       = "GIVE"
    url        = "/about-us/give"
    weight     = 1
    parent     = "menu.aboutus"

[[menu.main]]
    name       = "LEADERSHIP"
    url        = "/about-us/leadership"
    weight     = 2
    parent     = "menu.aboutus"

    [[menu.main]]
    name       = "PURPOSE"
    url        = "/about-us/purpose"
    weight     = 3
    parent     = "menu.aboutus"



#####################our fellowship menu##################################
     [[menu.main]]
    name       = "OUR FELLOWSHIP"
    identifier = "menu.fellowship"
    url        = "/our-fellowship/"
    weight     = 2

    
    

####################################resources menu##############################
     [[menu.main]]
    name       = "RESOURCES"
    identifier = "menu.resources"
    url        = "/"
    weight     = 3

    [[menu.main]]
    name       = "SERMONS"
    url        = "/resources/sermons"
    weight     = 1
    parent     = "menu.resources"
    [[menu.main]]

    name       = "BOOKS"
    url        = "/resources/books"
    weight     = 2
    parent     = "menu.resources"

    [[menu.main]]
    name       = "CHURCH"
    url        = "/resources/church"
    weight     = 3
    parent     = "menu.resources"

     [[menu.main]]
    name       = "MUSIC"
    url        = "/resources/music"
    weight     = 4
    parent     = "menu.resources"


###############events menu#######################################################
 [[menu.main]]
    name       = "EVENTS"
    identifier = "menu.events"
    url        = "/events/"
    weight     = 4



######################blog menu##############################################################
 [[menu.main]]
    name       = "BLOG"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

   

#######################join menu#############################################################################
 [[menu.main]]
    name       = "JOIN"
    identifier = "menu.join"
    url        = "/join/"
    weight     = 6

   
#####################contact us menu###########################
 [[menu.main]]
    name       = "CONTACT US"
    identifier = "menu.contact us"
    url        = "/contact-us/"
    weight     = 7

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"
    disqusShortname = "devcows"
    

    date_format = "January 2, 2006"

    [params.testimonials]
    enable = true
    
    
[params.widgets]
    categories = true
    tags = true
    search = true

#######################carousel home page###########################################
[params.carouselHomepage]
     enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


#########################################RECENT RESOURCES###########################################

[[params.recent_resources.resources]]
type = "SERMON"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"

[[params.recent_resources.resources]]
type = "SERMON"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"

[[params.recent_resources.resources]]
type = "SERMON"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"




[[params.recent_resources.resources]]
type = "BOOK"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"

[[params.recent_resources.resources]]
type = "BOOK"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"

[[params.recent_resources.resources]]
type = "BOOK"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"


[[params.recent_resources.resources]]
type = "MUSIC"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"

[[params.recent_resources.resources]]
type = "MUSIC"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"

[[params.recent_resources.resources]]
type = "MUSIC"
title = "The triumph of the Cross"
image = "/img/recentresources.jpg"


################################################ FEATURES ####################################################

    [params.features]
    enable = true
    cols = 4

    summaryLength = 70

############################################## RECENT POSTS #####################################################

[params.recent_posts]
    enable = true
    hide_summary = false

[params.footer.recent_posts]
    enable = true
  

############################################# LOGO###############################################################

[params.logo]
logoImg = "/img/apcLogo.png"
url = "/"



####################################footer#####################################################################

    [[params.footer.socials]]
    linkName = "Connect with us on Facebook!"
    url = "https://www.facebook.com/apcwo"
    iconClass = "bx bxl-facebook"

    [[params.footer.socials]]
    linkName = "Connect with us on Instagram!"
    url = "https://www.instagram.com/allpeopleschurchbangalore"
    iconClass = "bx bxl-instagram"

    [[params.footer.socials]]
    linkName = "Subscribe to our YouTube Channel and stay informed!"
    url = "https://www.youtube.com/allpeopleschurchbangalore"
    iconClass = "bx bxl-youtube"

    [[params.footer.socials]]
    linkName = "Listen on iTunes"
    url = "https://podcasts.apple.com/in/podcast/sunday-sermons/id1343675396"
    iconClass = "bx bxs-music"

    [[params.footer.socials]]
    linkName = "Subscribe through our RSS feed"
    url = "https://podcasts.apcwo.org/apc.xml"
    iconClass = "fa fa-rss"




    [[params.footer.footerLinks]]
    linkName = 'CHURCH'
    url = 'https://apcwo.org'

    [[params.footer.footerLinks]]
    linkName = 'BIBLE COLLEGE'
    url = 'https://apcbiblecollege.org'
    
    [[params.footer.footerLinks]]
    linkName = 'WORLD MISSIONS'
    url = 'https://apcworldmissions.org'

    [[params.footer.footerLinks]]
    linkName = 'SERMONS'
    url = 'https://apcwo.org/sermons'

    [[params.footer.footerLinks]]
    linkName = 'BOOKS'
    url = 'https://apcwo.org/books'

    [[params.footer.footerLinks]]
    linkName = 'DAILY DEVOTIONS'
    url = 'https://apcwo.org/devotionals'

    [[params.footer.footerLinks]]
    linkName = 'MUSIC'
    url = 'https://apcmusic.org'

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
